spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studentcourse
    username: postgres
    password: Zj#Pd&VY!h*E

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate